import assert from 'node:assert/strict';
import { createHmac, randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import { after, before, test } from 'node:test';
import type { INestApplication } from '@nestjs/common';
import { DateTime } from 'luxon';
import pg from 'pg';

const owner=new pg.Pool({connectionString:process.env.TEST_OWNER_DATABASE_URL}),authKey=Buffer.from(process.env.AUTH_HMAC_KEY!,'base64');const users:string[]=[],vendors:string[]=[];let app:INestApplication,baseUrl='';
const hash=(value:string)=>createHmac('sha256',authKey).update(value).digest('hex');
async function fixture(label:string){const userId=randomUUID(),vendorId=randomUUID(),slotId=randomUUID(),token=randomUUID(),routeIds=[randomUUID(),randomUUID()] as const,householdIds=Array.from({length:105},()=>randomUUID());users.push(userId);vendors.push(vendorId);await owner.query('INSERT INTO users(id,display_name,updated_at) VALUES($1,$2,now())',[userId,`Stop Owner ${label}`]);await owner.query(`INSERT INTO vendors(id,code,legal_name,display_name,status,timezone,currency,skip_cutoff_minutes,billing_day,updated_at) VALUES($1,$2,$3,$3,'active','Asia/Kolkata','INR',0,1,now())`,[vendorId,`stop-http-${vendorId}`,`Stop ${label}`]);await owner.query(`INSERT INTO vendor_memberships(id,vendor_id,user_id,role,status,joined_at,updated_at) VALUES($1,$2,$3,'vendor_owner','active',now(),now())`,[randomUUID(),vendorId,userId]);await owner.query("INSERT INTO mfa_factors(id,user_id,type,encrypted_secret,enabled_at) VALUES($1,$2,'totp','stops',now())",[randomUUID(),userId]);await owner.query(`INSERT INTO sessions(id,user_id,access_token_hash,refresh_token_hash,authentication_method,device_id,access_expires_at,expires_at,last_seen_at) VALUES($1,$2,$3,$4,'administrator_mfa','stops',now()+interval '1 hour',now()+interval '1 day',now())`,[randomUUID(),userId,hash(token),hash(randomUUID())]);await owner.query(`INSERT INTO delivery_slots(id,vendor_id,code,name,start_local_time,end_local_time,updated_at) VALUES($1,$2,$3,$4,'06:00','09:00',now())`,[slotId,vendorId,`STOP_HTTP_${label}`,`Stop ${label}`]);for(const [index,id] of routeIds.entries())await owner.query(`INSERT INTO routes(id,vendor_id,code,name,delivery_slot_id,updated_at) VALUES($1,$2,$3,$4,$5,now())`,[id,vendorId,`HTTP_${label}_${index}`,`HTTP Route ${index}`,slotId]);for(const [index,id] of householdIds.entries())await owner.query(`INSERT INTO households(id,vendor_id,account_number,name,address_line_1,city,region,postal_code,country_code,updated_at) VALUES($1,$2,$3,$4,'Road','Pune','MH','411001','IN',now())`,[id,vendorId,`HTTP-${label}-${index}`,`HTTP Household ${index}`]);return{userId,vendorId,slotId,token,routeIds,householdIds};}
function api(path:string,token:string,options:{method?:string;body?:unknown}={}){const headers:Record<string,string>={authorization:`Bearer ${token}`};if(options.body!==undefined)headers['content-type']='application/json';return fetch(`${baseUrl}${path}`,{method:options.method,headers,body:options.body===undefined?undefined:JSON.stringify(options.body)});}
async function json<T>(response:Response,status:number){if(response.status!==status)assert.fail(`expected ${status}, got ${response.status}: ${await response.text()}`);return response.json() as Promise<T>;}async function error(response:Response,status:number,code:string){assert.equal((await json<{code:string}>(response,status)).code,code);}
type Projection=Readonly<{routeId:string;routeVersion:number;deliverySlotId:string;serviceDate:string;startDate?:string;endDate?:string;stops:readonly Readonly<{id:string;householdId:string;sequence:number}>[];nextCursor?:string}>;
before(async()=>{const{createApp}=await import('../src/bootstrap/create-app.js');app=await createApp({logger:false});await app.listen(0,'127.0.0.1');const address=(app.getHttpServer()as Server).address();assert.ok(address&&typeof address!=='string');baseUrl=`http://127.0.0.1:${address.port}`;});
after(async()=>{await app?.close();await owner.query('DELETE FROM audit_events WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM route_stops WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM route_stop_plans WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM routes WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM households WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM delivery_slots WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM vendor_memberships WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM sessions WHERE user_id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM mfa_factors WHERE user_id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM vendors WHERE id=ANY($1::uuid[])',[vendors]);await owner.end();});

void test('atomic effective route stops preserve history, ordering, conflicts, empty plans, delete guards, audits, and rollback',async()=>{
  const current=await fixture('A'),other=await fixture('B'),today=DateTime.now().setZone('Asia/Kolkata').startOf('day'),date=(days:number)=>today.plus({days}).toISODate()!,listBase=`/v1/vendors/${current.vendorId}/routes/${current.routeIds[0]}/stops`,replaceBase=`${listBase}/replace`;
  assert.equal((await api(listBase,current.token,{method:'POST',body:{}})).status,404);
  await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:1,reason:'Initial order',householdIds:current.householdIds,unknown:true}}),400,'INVALID_REQUEST');
  await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:'2026-02-30',expectedVersion:1,reason:'Invalid date',householdIds:[]}}),400,'INVALID_ROUTE_DATE');
  await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(-1),expectedVersion:1,reason:'Past order',householdIds:[]}}),400,'INVALID_ROUTE_DATE');
  await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:1,reason:'Duplicate order',householdIds:[current.householdIds[0],current.householdIds[0]]}}),400,'INVALID_STOP_ORDER');
  const blocker=await owner.connect();let settled=false;let pending:Promise<Response>|undefined;try{await blocker.query('BEGIN');await blocker.query("SELECT pg_advisory_xact_lock(hashtextextended('routing-vendor-slot:' || $1::text || ':' || $2::text,0))",[current.vendorId,current.slotId]);pending=api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:1,reason:'Initial order',householdIds:[current.householdIds[0],current.householdIds[1]]}}).then(response=>{settled=true;return response;});await new Promise(resolve=>setTimeout(resolve,100));assert.equal(settled,false);}finally{await blocker.query('ROLLBACK');blocker.release();}assert.ok(pending);
  const initial=await json<Projection>(await pending,200);assert.equal(initial.routeVersion,2);assert.deepEqual(initial.stops.map(({householdId,sequence})=>({householdId,sequence})),[{householdId:current.householdIds[0],sequence:1},{householdId:current.householdIds[1],sequence:2}]);assert.deepEqual(Object.keys(initial).sort(),['deliverySlotId','routeId','routeVersion','serviceDate','startDate','stops']);
  const audit=(await owner.query<{action:string;old_value:Record<string,unknown>;new_value:Record<string,unknown>;reason:string}>("SELECT action,old_value,new_value,reason FROM audit_events WHERE vendor_id=$1 AND action='route_stops.replaced' ORDER BY created_at DESC,id DESC LIMIT 1",[current.vendorId])).rows[0];assert.equal(audit.action,'route_stops.replaced');assert.deepEqual(audit.old_value,{householdIds:[],effectiveDate:date(0),deliverySlotId:current.slotId,routeStatus:'active',routeVersion:1});assert.deepEqual(audit.new_value,{householdIds:[current.householdIds[0],current.householdIds[1]],effectiveDate:date(0),startDate:date(0),deliverySlotId:current.slotId,routeStatus:'active',routeVersion:2});assert.equal(audit.reason,'Initial order');
  await error(await api(`${listBase}?serviceDate=${date(0)}&cursor=not-a-cursor`,current.token),400,'INVALID_CURSOR');
  const listed=await json<Projection>(await api(`${listBase}?serviceDate=${date(0)}`,current.token),200);assert.deepEqual(listed.stops.map(({householdId})=>householdId),[current.householdIds[0],current.householdIds[1]]);
  await error(await api(`/v1/vendors/${other.vendorId}/routes/${current.routeIds[0]}/stops?serviceDate=${date(0)}`,current.token),403,'FORBIDDEN');
  await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(1),expectedVersion:2,reason:'Foreign household',householdIds:[other.householdIds[0]]}}),404,'ROUTE_HOUSEHOLD_NOT_FOUND');await owner.query("UPDATE households SET deleted_at=now(),deleted_by=$1,deletion_reason='Unavailable' WHERE id=$2",[current.userId,current.householdIds[4]]);await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(1),expectedVersion:2,reason:'Deleted household',householdIds:[current.householdIds[4]]}}),409,'ROUTE_HOUSEHOLD_NOT_AVAILABLE');
  const future=await json<Projection>(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(2),expectedVersion:2,reason:'Future order',householdIds:[current.householdIds[1],current.householdIds[2]]}}),200);assert.equal(future.routeVersion,3);const historical=await json<Projection>(await api(`${listBase}?serviceDate=${date(1)}`,current.token),200);assert.equal(historical.endDate,date(1));assert.deepEqual(historical.stops.map(({householdId})=>householdId),[current.householdIds[0],current.householdIds[1]]);
  const corrected=await json<Projection>(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(2),expectedVersion:3,reason:'Correct future',householdIds:[current.householdIds[2]]}}),200);assert.equal(corrected.routeVersion,4);assert.equal((await owner.query('SELECT 1 FROM route_stop_plans WHERE route_id=$1 AND superseded_at IS NOT NULL',[current.routeIds[0]])).rowCount,1);
  const otherReplace=`/v1/vendors/${current.vendorId}/routes/${current.routeIds[1]}/stops/replace`;await error(await api(otherReplace,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:1,reason:'Cross route',householdIds:[current.householdIds[0]]}}),409,'ROUTE_STOP_CONFLICT');
  const race=await Promise.all([api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(3),expectedVersion:4,reason:'Race A',householdIds:[current.householdIds[0]]}}),api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(3),expectedVersion:4,reason:'Race B',householdIds:[current.householdIds[1]]}})]);assert.deepEqual(race.map(({status})=>status).sort(),[200,409]);await error(race.find(({status})=>status===409)!,409,'ROUTE_VERSION_CONFLICT');const raceWinner=await json<Projection>(race.find(({status})=>status===200)!,200);
  await owner.query("UPDATE households SET status='inactive' WHERE id=$1",[current.householdIds[0]]);await error(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(4),expectedVersion:raceWinner.routeVersion,reason:'Unavailable',householdIds:[current.householdIds[0]]}}),409,'ROUTE_HOUSEHOLD_NOT_AVAILABLE');const empty=await json<Projection>(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:raceWinner.routeVersion,reason:'End all',householdIds:[]}}),200);assert.equal(empty.stops.length,0);
  const deleteBase=`/v1/vendors/${current.vendorId}/routes/${current.routeIds[1]}`;await owner.query("UPDATE routes SET status='inactive' WHERE id=$1",[current.routeIds[1]]);await error(await api(`${deleteBase}/stops/replace`,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:1,reason:'Inactive route',householdIds:[]}}),409,'ROUTE_STATE_CONFLICT');await owner.query("UPDATE routes SET status='active' WHERE id=$1",[current.routeIds[1]]);const seeded=await json<Projection>(await api(`${deleteBase}/stops/replace`,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:1,reason:'Seed delete guard',householdIds:[current.householdIds[1]]}}),200);const futureEmpty=await json<Projection>(await api(`${deleteBase}/stops/replace`,current.token,{method:'POST',body:{effectiveDate:date(2),expectedVersion:seeded.routeVersion,reason:'Future empty',householdIds:[]}}),200);await owner.query("UPDATE routes SET status='inactive' WHERE id=$1",[current.routeIds[1]]);await error(await api(deleteBase,current.token,{method:'DELETE',body:{expectedVersion:futureEmpty.routeVersion,reason:'Too early'}}),409,'ROUTE_DELETE_REQUIRES_EMPTY');await owner.query("UPDATE routes SET status='active' WHERE id=$1",[current.routeIds[1]]);const todayEmpty=await json<Projection>(await api(`${deleteBase}/stops/replace`,current.token,{method:'POST',body:{effectiveDate:date(0),expectedVersion:futureEmpty.routeVersion,reason:'Empty now',householdIds:[]}}),200);await owner.query("UPDATE routes SET status='inactive' WHERE id=$1",[current.routeIds[1]]);assert.equal((await api(deleteBase,current.token,{method:'DELETE',body:{expectedVersion:todayEmpty.routeVersion,reason:'Archive empty route'}})).status,204);
  const suffix=randomUUID().replaceAll('-',''),fn=`reject_stop_audit_${suffix}`,trigger=`reject_stop_audit_trigger_${suffix}`;const before=(await owner.query<{version:number}>('SELECT version FROM routes WHERE id=$1',[current.routeIds[0]])).rows[0].version;try{await owner.query(`CREATE FUNCTION ${fn}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='route_stops.replaced' THEN RAISE EXCEPTION 'forced'; END IF; RETURN NEW; END $$`);await owner.query(`CREATE TRIGGER ${trigger} BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION ${fn}()`);assert.equal((await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(5),expectedVersion:before,reason:'Rollback',householdIds:[]}})).status,500);}finally{await owner.query(`DROP TRIGGER IF EXISTS ${trigger} ON audit_events`);await owner.query(`DROP FUNCTION IF EXISTS ${fn}()`);}assert.equal((await owner.query<{version:number}>('SELECT version FROM routes WHERE id=$1',[current.routeIds[0]])).rows[0].version,before);
  await owner.query("UPDATE households SET status='active',deleted_at=NULL,deleted_by=NULL,deletion_reason=NULL WHERE vendor_id=$1",[current.vendorId]);const page=await json<Projection>(await api(replaceBase,current.token,{method:'POST',body:{effectiveDate:date(6),expectedVersion:before,reason:'Large route',householdIds:current.householdIds.slice(0,101)}}),200);assert.equal(page.stops.length,25);assert.ok(page.nextCursor);const second=await json<Projection>(await api(`${listBase}?serviceDate=${date(6)}&limit=10&cursor=${page.nextCursor}`,current.token),200);assert.deepEqual(second.stops.map(({householdId})=>householdId),current.householdIds.slice(25,35));const filtered=await json<Projection>(await api(`${listBase}?serviceDate=${date(5)}&cursor=${page.nextCursor}`,current.token),200);assert.deepEqual(filtered.stops,[]);
});
