import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import pg from 'pg';

const runtime=new pg.Pool({connectionString:process.env.DATABASE_URL}),owner=new pg.Pool({connectionString:process.env.TEST_OWNER_DATABASE_URL});test.after(()=>Promise.all([runtime.end(),owner.end()]));
async function fixture(label:string){const vendorId=randomUUID(),slotId=randomUUID(),ownerId=randomUUID(),agentIds=[randomUUID(),randomUUID()]as const,membershipIds=[randomUUID(),randomUUID()]as const,routeIds=[randomUUID(),randomUUID()]as const;for(const[id,name]of[[ownerId,`Owner ${label}`],[agentIds[0],`Agent A ${label}`],[agentIds[1],`Agent B ${label}`]]as const)await owner.query('INSERT INTO users(id,display_name,updated_at)VALUES($1,$2,now())',[id,name]);await owner.query("INSERT INTO vendors(id,code,legal_name,display_name,status,timezone,currency,skip_cutoff_minutes,billing_day,updated_at)VALUES($1,$2,$3,$3,'active','Asia/Kolkata','INR',0,1,now())",[vendorId,`assign-${vendorId}`,`Assign ${label}`]);await owner.query("INSERT INTO delivery_slots(id,vendor_id,code,name,start_local_time,end_local_time,updated_at)VALUES($1,$2,$3,$4,'06:00','09:00',now())",[slotId,vendorId,`ASSIGN_${label}`,`Assign ${label}`]);for(const[i,id]of routeIds.entries())await owner.query('INSERT INTO routes(id,vendor_id,code,name,delivery_slot_id,updated_at)VALUES($1,$2,$3,$4,$5,now())',[id,vendorId,`ASSIGN_${label}_${i}`,`Route ${i}`,slotId]);for(const[i,id]of membershipIds.entries())await owner.query("INSERT INTO vendor_memberships(id,vendor_id,user_id,role,status,joined_at,updated_at)VALUES($1,$2,$3,'delivery_agent','active',now(),now())",[id,vendorId,agentIds[i]]);return{vendorId,slotId,ownerId,agentIds,membershipIds,routeIds};}
type Fixture=Awaited<ReturnType<typeof fixture>>;async function cleanup(values:readonly Fixture[]){const vendors=values.map(v=>v.vendorId),users=values.flatMap(v=>[v.ownerId,...v.agentIds]);await owner.query('DELETE FROM route_assignments WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM routes WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM delivery_slots WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM vendor_memberships WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM vendors WHERE id=ANY($1::uuid[])',[vendors]);}
const insert=(v:Fixture,routeId:string,agentId:string,date='2099-01-01',status='assigned')=>owner.query<{id:string}>("INSERT INTO route_assignments(id,vendor_id,route_id,delivery_slot_id,agent_membership_id,service_date,status,created_by,updated_by,cancelled_at,cancellation_reason,updated_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,CASE WHEN $7='cancelled' THEN now() END,CASE WHEN $7='cancelled' THEN 'Cancelled route' END,now())RETURNING id",[randomUUID(),v.vendorId,routeId,v.slotId,agentId,date,status,v.ownerId]);
async function asTenant(vendorId:string,work:(client:pg.PoolClient)=>Promise<void>){const client=await runtime.connect();try{await client.query('BEGIN');await client.query("SELECT set_config('app.vendor_id',$1,true)",[vendorId]);await work(client);}finally{await client.query('ROLLBACK');client.release();}}

void test('assignment schema publishes tenant-safe constraints, indexes, forced RLS, and no delete grant',async()=>{for(const name of['route_assignments_vendor_id_route_id_service_date_key','route_assignments_route_fkey','route_assignments_agent_membership_fkey','route_assignments_status_consistency_check'])assert.equal((await owner.query('SELECT 1 FROM pg_constraint WHERE conname=$1',[name])).rowCount,1);assert.equal((await owner.query("SELECT 1 FROM pg_indexes WHERE indexname='route_assignments_agent_slot_date_assigned_key'")).rowCount,1);assert.deepEqual((await owner.query("SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='route_assignments'")).rows,[{relrowsecurity:true,relforcerowsecurity:true}]);assert.equal((await owner.query<{allowed:boolean}>("SELECT has_table_privilege('milktrack_app','route_assignments','DELETE') allowed")).rows[0]?.allowed,false);});
void test('assignment constraints preserve exact route/date and assigned agent/slot/date uniqueness',async()=>{const values=[await fixture('A'),await fixture('B')]as const;try{await insert(values[0],values[0].routeIds[0],values[0].membershipIds[0]);await assert.rejects(insert(values[0],values[0].routeIds[0],values[0].membershipIds[1]),/route_assignments_vendor_id_route_id_service_date_key/);await assert.rejects(insert(values[0],values[0].routeIds[1],values[0].membershipIds[0]),/route_assignments_agent_slot_date_assigned_key/);assert.equal((await insert(values[0],values[0].routeIds[1],values[0].membershipIds[0],'2099-01-01','cancelled')).rowCount,1);await assert.rejects(insert(values[0],values[0].routeIds[1],values[1].membershipIds[0],'2099-01-02'),/route_assignments_agent_membership_fkey/);await assert.rejects(owner.query("INSERT INTO route_assignments(id,vendor_id,route_id,delivery_slot_id,agent_membership_id,service_date,status,created_by,updated_by,cancelled_at,updated_at)VALUES($1,$2,$3,$4,$5,'2099-02-01','cancelled',$6,$6,now(),now())",[randomUUID(),values[0].vendorId,values[0].routeIds[0],values[0].slotId,values[0].membershipIds[1],values[0].ownerId]),/route_assignments_status_consistency_check/);await assert.rejects(owner.query("INSERT INTO route_assignments(id,vendor_id,route_id,delivery_slot_id,agent_membership_id,service_date,status,created_by,updated_by,cancelled_at,cancellation_reason,updated_at)VALUES($1,$2,$3,$4,$5,'2099-02-02','cancelled',$6,$6,now(),' untrimmed ',now())",[randomUUID(),values[0].vendorId,values[0].routeIds[0],values[0].slotId,values[0].membershipIds[1],values[0].ownerId]),/route_assignments_status_consistency_check/);}finally{await cleanup(values);}});
void test('runtime assignment access is tenant-isolated and immutable identity columns cannot be changed',async()=>{const values=[await fixture('C'),await fixture('D')]as const,ids=[(await insert(values[0],values[0].routeIds[0],values[0].membershipIds[0])).rows[0].id,(await insert(values[1],values[1].routeIds[0],values[1].membershipIds[0])).rows[0].id];try{for(const[index,other]of[[0,1],[1,0]]as const){await asTenant(values[index].vendorId,async client=>{assert.equal((await client.query('SELECT id FROM route_assignments WHERE id=$1',[ids[index]])).rowCount,1);assert.equal((await client.query('SELECT id FROM route_assignments WHERE id=$1',[ids[other]])).rowCount,0);await assert.rejects(client.query('UPDATE route_assignments SET service_date=$1 WHERE id=$2',['2099-01-02',ids[index]]),/permission denied/);});await asTenant(values[index].vendorId,async client=>{await assert.rejects(client.query('DELETE FROM route_assignments WHERE id=$1',[ids[index]]),/permission denied/);});}}finally{await cleanup(values);}});
