import assert from 'node:assert/strict';
import { createHmac,randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import { after,before,test } from 'node:test';
import type { INestApplication } from '@nestjs/common';
import { DateTime } from 'luxon';
import pg from 'pg';
import { TenantTransactionRunner } from '../src/common/application/transaction-context.js';
import { RoutingScheduleService } from '../src/routing/application/routing-schedule.service.js';

const owner=new pg.Pool({connectionString:process.env.TEST_OWNER_DATABASE_URL}),key=Buffer.from(process.env.AUTH_HMAC_KEY!,'base64'),users:string[]=[],vendors:string[]=[];let app:INestApplication,baseUrl='';const hash=(v:string)=>createHmac('sha256',key).update(v).digest('hex');
async function session(userId:string,method:'administrator_mfa'|'phone_otp'){const token=randomUUID();await owner.query('INSERT INTO sessions(id,user_id,access_token_hash,refresh_token_hash,authentication_method,device_id,access_expires_at,expires_at,last_seen_at)VALUES($1,$2,$3,$4,$5,$6,now()+interval\'1 hour\',now()+interval\'1 day\',now())',[randomUUID(),userId,hash(token),hash(randomUUID()),method,`assign-${userId}`]);return token;}
async function fixture(label:string){const vendorId=randomUUID(),slotId=randomUUID(),ownerId=randomUUID(),agentUsers=[randomUUID(),randomUUID()]as const,agentMemberships=[randomUUID(),randomUUID()]as const,ownerMembership=randomUUID(),routeIds=[randomUUID(),randomUUID()]as const;vendors.push(vendorId);users.push(ownerId,...agentUsers);for(const[id,name]of[[ownerId,`Owner ${label}`],[agentUsers[0],`Agent A ${label}`],[agentUsers[1],`Agent B ${label}`]]as const)await owner.query('INSERT INTO users(id,display_name,updated_at)VALUES($1,$2,now())',[id,name]);await owner.query("INSERT INTO vendors(id,code,legal_name,display_name,status,timezone,currency,skip_cutoff_minutes,billing_day,updated_at)VALUES($1,$2,$3,$3,'active','Asia/Kolkata','INR',0,1,now())",[vendorId,`assign-http-${vendorId}`,`Assign ${label}`]);await owner.query("INSERT INTO vendor_memberships(id,vendor_id,user_id,role,status,joined_at,updated_at)VALUES($1,$2,$3,'vendor_owner','active',now(),now())",[ownerMembership,vendorId,ownerId]);for(const[i,id]of agentMemberships.entries())await owner.query("INSERT INTO vendor_memberships(id,vendor_id,user_id,role,status,joined_at,updated_at)VALUES($1,$2,$3,'delivery_agent','active',now(),now())",[id,vendorId,agentUsers[i]]);await owner.query("INSERT INTO mfa_factors(id,user_id,type,encrypted_secret,enabled_at)VALUES($1,$2,'totp','assign',now())",[randomUUID(),ownerId]);const ownerToken=await session(ownerId,'administrator_mfa'),agentToken=await session(agentUsers[0],'phone_otp');await owner.query("INSERT INTO delivery_slots(id,vendor_id,code,name,start_local_time,end_local_time,updated_at)VALUES($1,$2,$3,$4,'06:00','09:00',now())",[slotId,vendorId,`ASSIGN_HTTP_${label}`,`Assign ${label}`]);for(const[i,id]of routeIds.entries())await owner.query('INSERT INTO routes(id,vendor_id,code,name,delivery_slot_id,updated_at)VALUES($1,$2,$3,$4,$5,now())',[id,vendorId,`ASSIGN_HTTP_${label}_${i}`,`Assign route ${i}`,slotId]);return{vendorId,slotId,ownerId,ownerMembership,ownerToken,agentUsers,agentMemberships,agentToken,routeIds};}
function api(path:string,token:string,options:{method?:string;body?:unknown}={}){const headers:Record<string,string>={authorization:`Bearer ${token}`};if(options.body!==undefined)headers['content-type']='application/json';return fetch(`${baseUrl}${path}`,{method:options.method,headers,body:options.body===undefined?undefined:JSON.stringify(options.body)});}async function json<T>(response:Response,status:number){if(response.status!==status)assert.fail(`expected ${status}, got ${response.status}: ${await response.text()}`);return response.json()as Promise<T>;}async function error(response:Response,status:number,code:string){assert.equal((await json<{code:string}>(response,status)).code,code);}type Assignment={id:string;routeId:string;deliverySlotId:string;agentMembershipId:string;serviceDate:string;status:string;routeVersion?:number};
before(async()=>{const{createApp}=await import('../src/bootstrap/create-app.js');app=await createApp({logger:false});await app.listen(0,'127.0.0.1');const address=(app.getHttpServer()as Server).address();assert.ok(address&&typeof address!=='string');baseUrl=`http://127.0.0.1:${address.port}`;});after(async()=>{await app?.close();await owner.query('DELETE FROM audit_events WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM route_assignments WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM routes WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM delivery_slots WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM vendor_memberships WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM sessions WHERE user_id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM mfa_factors WHERE user_id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM vendors WHERE id=ANY($1::uuid[])',[vendors]);await owner.end();});

void test('dated assignments enforce membership, state, self scope, conflicts, delete guards, audits, and rollback',async()=>{const current=await fixture('A'),other=await fixture('B'),today=DateTime.now().setZone('Asia/Kolkata').startOf('day'),date=(days:number)=>today.plus({days}).toISODate()!,base=`/v1/vendors/${current.vendorId}/routes/${current.routeIds[0]}/assignments`,put=`${base}/${date(1)}`;
  await error(await api(`${base}/2026-02-30`,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:1,reason:'Invalid date'}}),400,'INVALID_ROUTE_DATE');await error(await api(`${base}/${date(-1)}`,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:1,reason:'Past date'}}),400,'INVALID_ROUTE_DATE');
  await error(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:other.agentMemberships[0],expectedVersion:1,reason:'Foreign agent'}}),404,'ROUTE_AGENT_NOT_FOUND');await error(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.ownerMembership,expectedVersion:1,reason:'Wrong role'}}),409,'ROUTE_AGENT_NOT_AVAILABLE');
  await owner.query("UPDATE vendor_memberships SET status='ended',ended_at=now() WHERE id=$1",[current.agentMemberships[0]]);await error(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:1,reason:'Ended agent'}}),409,'ROUTE_AGENT_NOT_AVAILABLE');await owner.query("UPDATE vendor_memberships SET status='active',ended_at=NULL,deleted_at=now(),deleted_by=$1,deletion_reason='Deleted agent' WHERE id=$2",[current.ownerId,current.agentMemberships[0]]);await error(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:1,reason:'Deleted agent'}}),404,'ROUTE_AGENT_NOT_FOUND');await owner.query("UPDATE vendor_memberships SET deleted_at=NULL,deleted_by=NULL,deletion_reason=NULL WHERE id=$1",[current.agentMemberships[0]]);
  const created=await json<Assignment>(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:1,reason:'Assign route'}}),201);assert.equal(created.routeVersion,2);assert.equal(created.agentMembershipId,current.agentMemberships[0]);
  await error(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:2,reason:'Same agent'}}),409,'ROUTE_STATE_CONFLICT');assert.equal((await owner.query<{version:number}>('SELECT version FROM routes WHERE id=$1',[current.routeIds[0]])).rows[0].version,2);
  const self=`/v1/agent/vendors/${current.vendorId}/route-assignments?serviceDate=${date(1)}`;assert.deepEqual((await json<{items:Assignment[]}>(await api(self,current.agentToken),200)).items.map(({id})=>id),[created.id]);await error(await api(`/v1/agent/vendors/${other.vendorId}/route-assignments?serviceDate=${date(1)}`,current.agentToken),403,'FORBIDDEN');
  const projection=await app.get(TenantTransactionRunner).run(current.vendorId,tx=>app.get(RoutingScheduleService).project(tx,current.vendorId,date(1)));assert.equal(projection.length,2);assert.deepEqual(projection.find(({routeId})=>routeId===current.routeIds[0])?.assignment,{assignmentId:created.id,agentMembershipId:current.agentMemberships[0]});assert.deepEqual(projection.find(({routeId})=>routeId===current.routeIds[1])?.stops,[]);
  const directId=randomUUID();await owner.query("INSERT INTO route_assignments(id,vendor_id,route_id,delivery_slot_id,agent_membership_id,service_date,status,created_by,updated_by,updated_at)VALUES($1,$2,$3,$4,$5,$6,'assigned',$7,$7,now())",[directId,current.vendorId,current.routeIds[0],current.slotId,current.agentMemberships[1],date(2),current.ownerId]);const page=await json<{items:Assignment[];nextCursor?:string}>(await api(`${base}?fromDate=${date(1)}&toDate=${date(2)}&status=assigned&limit=1`,current.ownerToken),200);assert.equal(page.items.length,1);assert.ok(page.nextCursor);assert.equal((await json<{items:Assignment[]}>(await api(`${base}?fromDate=${date(1)}&toDate=${date(2)}&status=assigned&limit=1&cursor=${page.nextCursor}`,current.ownerToken),200)).items.length,1);await error(await api(`${base}?cursor=bad`,current.ownerToken),400,'INVALID_CURSOR');
  const reassigned=await json<Assignment>(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[1],expectedVersion:2,reason:'Reassign route'}}),200);assert.equal(reassigned.routeVersion,3);assert.deepEqual((await json<{items:Assignment[]}>(await api(self,current.agentToken),200)).items,[]);
  await error(await api(`/v1/vendors/${current.vendorId}/routes/${current.routeIds[1]}/assignments/${date(1)}`,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[1],expectedVersion:1,reason:'Conflicting route'}}),409,'ROUTE_ASSIGNMENT_CONFLICT');
  await owner.query("UPDATE vendor_memberships SET status='ended',ended_at=now() WHERE id=$1",[current.agentMemberships[1]]);const cancelled=await json<Assignment>(await api(`${put}/cancel`,current.ownerToken,{method:'POST',body:{expectedVersion:3,reason:'Cancel route'}}),200);assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.routeVersion,4);await owner.query("UPDATE vendor_memberships SET status='active',ended_at=NULL WHERE id=$1",[current.agentMemberships[1]]);
  const active=await json<Assignment>(await api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[1],expectedVersion:4,reason:'Restore route'}}),200);assert.equal(active.routeVersion,5);
  const race=await Promise.all([api(`${put}/cancel`,current.ownerToken,{method:'POST',body:{expectedVersion:5,reason:'Race cancel'}}),api(put,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:5,reason:'Race reassign'}})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);await error(race.find(r=>r.status===409)!,409,'ROUTE_VERSION_CONFLICT');
  await owner.query('DELETE FROM route_assignments WHERE id=$1',[directId]);const version=(await owner.query<{version:number}>('SELECT version FROM routes WHERE id=$1',[current.routeIds[0]])).rows[0].version;const row=(await owner.query<{status:string}>('SELECT status FROM route_assignments WHERE id=$1',[created.id])).rows[0];if(row.status==='assigned')await json(await api(`${put}/cancel`,current.ownerToken,{method:'POST',body:{expectedVersion:version,reason:'Prepare delete'}}),200);
  const deleteVersion=(await owner.query<{version:number}>('SELECT version FROM routes WHERE id=$1',[current.routeIds[0]])).rows[0].version;await owner.query("UPDATE routes SET status='inactive' WHERE id=$1",[current.routeIds[0]]);assert.equal((await api(`/v1/vendors/${current.vendorId}/routes/${current.routeIds[0]}`,current.ownerToken,{method:'DELETE',body:{expectedVersion:deleteVersion,reason:'Delete empty route'}})).status,204);
  const actions=(await owner.query<{action:string}>('SELECT action FROM audit_events WHERE vendor_id=$1 AND action LIKE\'route_assignment.%\'',[current.vendorId])).rows.map(r=>r.action);for(const action of['route_assignment.assigned','route_assignment.reassigned','route_assignment.cancelled'])assert.ok(actions.includes(action));
  const rollbackRoute=current.routeIds[1],rollbackPath=`/v1/vendors/${current.vendorId}/routes/${rollbackRoute}/assignments/${date(2)}`,suffix=randomUUID().replaceAll('-',''),fn=`reject_assignment_audit_${suffix}`,trigger=`reject_assignment_audit_trigger_${suffix}`;try{await owner.query(`CREATE FUNCTION ${fn}()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='route_assignment.assigned' THEN RAISE EXCEPTION 'forced';END IF;RETURN NEW;END$$`);await owner.query(`CREATE TRIGGER ${trigger} BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION ${fn}()`);assert.equal((await api(rollbackPath,current.ownerToken,{method:'PUT',body:{agentMembershipId:current.agentMemberships[0],expectedVersion:1,reason:'Rollback audit'}})).status,500);}finally{await owner.query(`DROP TRIGGER IF EXISTS ${trigger} ON audit_events`);await owner.query(`DROP FUNCTION IF EXISTS ${fn}()`);}assert.equal((await owner.query('SELECT 1 FROM route_assignments WHERE route_id=$1 AND service_date=$2',[rollbackRoute,date(2)])).rowCount,0);assert.equal((await owner.query<{version:number}>('SELECT version FROM routes WHERE id=$1',[rollbackRoute])).rows[0].version,1);
});

void test('delete guard blocks only current/future assigned rows, not cancelled or historical assignments',async()=>{const value=await fixture('DELETE'),today=DateTime.now().setZone('Asia/Kolkata').startOf('day'),date=(days:number)=>today.plus({days}).toISODate()!,routeId=value.routeIds[0],assignmentPath=`/v1/vendors/${value.vendorId}/routes/${routeId}/assignments/${date(1)}`,routePath=`/v1/vendors/${value.vendorId}/routes/${routeId}`;await json(await api(assignmentPath,value.ownerToken,{method:'PUT',body:{agentMembershipId:value.agentMemberships[0],expectedVersion:1,reason:'Future assignment'}}),201);await owner.query("UPDATE routes SET status='inactive' WHERE id=$1",[routeId]);await error(await api(routePath,value.ownerToken,{method:'DELETE',body:{expectedVersion:2,reason:'Blocked route'}}),409,'ROUTE_DELETE_REQUIRES_EMPTY');await json(await api(`${assignmentPath}/cancel`,value.ownerToken,{method:'POST',body:{expectedVersion:2,reason:'Cancel future'}}),200);await owner.query("INSERT INTO route_assignments(id,vendor_id,route_id,delivery_slot_id,agent_membership_id,service_date,status,created_by,updated_by,updated_at)VALUES($1,$2,$3,$4,$5,$6,'assigned',$7,$7,now())",[randomUUID(),value.vendorId,routeId,value.slotId,value.agentMemberships[0],date(-1),value.ownerId]);assert.equal((await api(routePath,value.ownerToken,{method:'DELETE',body:{expectedVersion:3,reason:'Archive route'}})).status,204);});
