import assert from 'node:assert/strict';
import { createHmac, randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import { after, before, test } from 'node:test';
import type { INestApplication } from '@nestjs/common';
import pg from 'pg';

const owner = new pg.Pool({ connectionString: process.env.TEST_OWNER_DATABASE_URL }); const authKey = Buffer.from(process.env.AUTH_HMAC_KEY!, 'base64');
const users: string[] = []; const vendors: string[] = []; let app: INestApplication; let baseUrl = '';
const hash = (value: string) => createHmac('sha256', authKey).update(value).digest('hex');
async function fixture(label: string) { const userId=randomUUID(),vendorId=randomUUID(),slotId=randomUUID(),token=randomUUID(); users.push(userId); vendors.push(vendorId); await owner.query('INSERT INTO users(id,display_name,updated_at) VALUES($1,$2,now())',[userId,`Route Owner ${label}`]); await owner.query(`INSERT INTO vendors(id,code,legal_name,display_name,status,timezone,currency,skip_cutoff_minutes,billing_day,updated_at) VALUES($1,$2,$3,$3,'active','Asia/Kolkata','INR',0,1,now())`,[vendorId,`route-${vendorId}`,`Route ${label}`]); await owner.query(`INSERT INTO vendor_memberships(id,vendor_id,user_id,role,status,joined_at,updated_at) VALUES($1,$2,$3,'vendor_owner','active',now(),now())`,[randomUUID(),vendorId,userId]); await owner.query("INSERT INTO mfa_factors(id,user_id,type,encrypted_secret,enabled_at) VALUES($1,$2,'totp','routes',now())",[randomUUID(),userId]); await owner.query(`INSERT INTO sessions(id,user_id,access_token_hash,refresh_token_hash,authentication_method,device_id,access_expires_at,expires_at,last_seen_at) VALUES($1,$2,$3,$4,'administrator_mfa','routes',now()+interval '1 hour',now()+interval '1 day',now())`,[randomUUID(),userId,hash(token),hash(randomUUID())]); await owner.query(`INSERT INTO delivery_slots(id,vendor_id,code,name,start_local_time,end_local_time,updated_at) VALUES($1,$2,$3,$4,'06:00','09:00',now())`,[slotId,vendorId,`ROUTE_${label}`,`Route ${label}`]); return {vendorId,slotId,token}; }
function api(path:string,token:string,options:{method?:string;body?:unknown}={}) { const headers:Record<string,string>={authorization:`Bearer ${token}`}; if(options.body!==undefined) headers['content-type']='application/json'; return fetch(`${baseUrl}${path}`,{method:options.method,headers,body:options.body===undefined?undefined:JSON.stringify(options.body)}); }
async function json<T>(response:Response,status:number){ if(response.status!==status) assert.fail(`expected ${status}, got ${response.status}: ${await response.text()}`); return response.json() as Promise<T>; }
async function error(response:Response,status:number,code?:string){const body=await json<{code:string}>(response,status);if(code)assert.equal(body.code,code);}
type Route=Readonly<{id:string;vendorId:string;code:string;name:string;deliverySlotId:string;status:'active'|'inactive';version:number;createdAt:string;updatedAt:string}>;

before(async()=>{const {createApp}=await import('../src/bootstrap/create-app.js');app=await createApp({logger:false});await app.listen(0,'127.0.0.1');const address=(app.getHttpServer() as Server).address();assert.ok(address&&typeof address!=='string');baseUrl=`http://127.0.0.1:${address.port}`;});
after(async()=>{await app?.close();await owner.query('DELETE FROM audit_events WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM routes WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM delivery_slots WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM vendor_memberships WHERE vendor_id=ANY($1::uuid[])',[vendors]);await owner.query('DELETE FROM sessions WHERE user_id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM mfa_factors WHERE user_id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[users]);await owner.query('DELETE FROM vendors WHERE id=ANY($1::uuid[])',[vendors]);await owner.end();});

void test('route definitions enforce strict DTOs, tenant safety, cursor filters, lifecycle versions, soft-delete reuse, audits, and rollback',async()=>{
  const current=await fixture('A'),other=await fixture('B'),base=`/v1/vendors/${current.vendorId}/routes`;
  await error(await api(base,current.token,{method:'POST',body:{code:'AM',name:'Morning',deliverySlotId:current.slotId,unknown:true}}),400);
  await error(await api(base,current.token,{method:'POST',body:{code:'!',name:'Morning',deliverySlotId:current.slotId}}),400,'INVALID_ROUTE_CODE');
  await error(await api(base,current.token,{method:'POST',body:{code:'VALID',name:'',deliverySlotId:current.slotId}}),400,'INVALID_ROUTE_NAME');
  const created=await json<Route>(await api(base,current.token,{method:'POST',body:{code:'am_route',name:' Morning Route ',deliverySlotId:current.slotId}}),201);
  assert.deepEqual({code:created.code,name:created.name,status:created.status,version:created.version},{code:'AM_ROUTE',name:'Morning Route',status:'active',version:1}); assert.deepEqual(Object.keys(created).sort(),['code','createdAt','deliverySlotId','id','name','status','updatedAt','vendorId','version']);
  await error(await api(`${base}/${created.id}`,other.token),403,'FORBIDDEN'); await error(await api(`/v1/vendors/${other.vendorId}/routes/${created.id}`,current.token),403,'FORBIDDEN');
  await error(await api(`${base}/${created.id}`,current.token,{method:'PATCH',body:{name:'',expectedVersion:1}}),400,'INVALID_ROUTE_NAME');
  await error(await api(`${base}/${created.id}`,current.token,{method:'PATCH',body:{name:'Changed',expectedVersion:1,code:'NEW'}}),400);
  const competing=await Promise.all([api(`${base}/${created.id}`,current.token,{method:'PATCH',body:{name:'East Morning',expectedVersion:1}}),api(`${base}/${created.id}`,current.token,{method:'PATCH',body:{name:'West Morning',expectedVersion:1}})]); assert.deepEqual(competing.map(({status})=>status).sort(),[200,409]); await error(competing.find(({status})=>status===409)!,409,'ROUTE_VERSION_CONFLICT');
  const renamed=await json<Route>(competing.find(({status})=>status===200)!,200); assert.equal(renamed.version,2);
  await error(await api(`${base}/${created.id}/deactivate`,current.token,{method:'POST',body:{expectedVersion:2,reason:'x'}}),400,'INVALID_REASON');
  const extras:Route[]=[]; for(const [code,name] of [['R1','Filtered one'],['R2','Filtered two']] as const) extras.push(await json<Route>(await api(base,current.token,{method:'POST',body:{code,name,deliverySlotId:current.slotId}}),201)); await owner.query('UPDATE routes SET created_at=$1 WHERE id=ANY($2::uuid[])',[new Date('2026-07-20T00:00:00Z'),extras.map(({id})=>id)]); const first=await json<{items:Route[];nextCursor:string}>(await api(`${base}?search=filtered&deliverySlotId=${current.slotId}&limit=1`,current.token),200); const second=await json<{items:Route[]}>(await api(`${base}?search=filtered&deliverySlotId=${current.slotId}&limit=1&cursor=${encodeURIComponent(first.nextCursor)}`,current.token),200); assert.equal(first.items.length,1);assert.equal(second.items.length,1);
  await error(await api(`${base}/${created.id}`,current.token,{method:'DELETE',body:{expectedVersion:2,reason:'Archive route'}}),409,'ROUTE_DELETE_REQUIRES_INACTIVE');
  const inactive=await json<Route>(await api(`${base}/${created.id}/deactivate`,current.token,{method:'POST',body:{expectedVersion:2,reason:'Seasonal closure'}}),200);assert.equal(inactive.version,3);
  assert.equal((await api(`${base}/${created.id}`,current.token,{method:'DELETE',body:{expectedVersion:3,reason:'Archive route'}})).status,204); await error(await api(`${base}/${created.id}`,current.token),404,'ROUTE_NOT_FOUND');
  const replacement=await json<Route>(await api(base,current.token,{method:'POST',body:{code:'AM_ROUTE',name:'Replacement',deliverySlotId:current.slotId}}),201); await error(await api(`${base}/${created.id}/restore`,current.token,{method:'POST',body:{expectedVersion:4,reason:'Restore route'}}),409,'ROUTE_CODE_CONFLICT');
  const replacementInactive=await json<Route>(await api(`${base}/${replacement.id}/deactivate`,current.token,{method:'POST',body:{expectedVersion:1,reason:'Retire replacement'}}),200);assert.equal(replacementInactive.version,2);assert.equal((await api(`${base}/${replacement.id}`,current.token,{method:'DELETE',body:{expectedVersion:2,reason:'Remove replacement'}})).status,204);
  const restored=await json<Route>(await api(`${base}/${created.id}/restore`,current.token,{method:'POST',body:{expectedVersion:4,reason:'Restore route'}}),200);assert.equal(restored.status,'inactive');assert.equal(restored.version,5);
  await owner.query('UPDATE delivery_slots SET active=false WHERE id=$1',[current.slotId]);await error(await api(`${base}/${created.id}/reactivate`,current.token,{method:'POST',body:{expectedVersion:5,reason:'Resume service'}}),409,'ROUTE_SLOT_NOT_AVAILABLE');await owner.query('UPDATE delivery_slots SET active=true WHERE id=$1',[current.slotId]);const active=await json<Route>(await api(`${base}/${created.id}/reactivate`,current.token,{method:'POST',body:{expectedVersion:5,reason:'Resume service'}}),200);assert.equal(active.version,6);
  const suffix=randomUUID().replaceAll('-',''),fn=`reject_route_audit_fn_${suffix}`,trigger=`reject_route_audit_${suffix}`;try{await owner.query(`CREATE FUNCTION ${fn}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='route.renamed' THEN RAISE EXCEPTION 'forced'; END IF; RETURN NEW; END $$`);await owner.query(`CREATE TRIGGER ${trigger} BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION ${fn}()`);assert.equal((await api(`${base}/${created.id}`,current.token,{method:'PATCH',body:{name:'Must rollback',expectedVersion:6}})).status,500);}finally{await owner.query(`DROP TRIGGER IF EXISTS ${trigger} ON audit_events`);await owner.query(`DROP FUNCTION IF EXISTS ${fn}()`);}assert.equal((await owner.query<{name:string}>('SELECT name FROM routes WHERE id=$1',[created.id])).rows[0]?.name,renamed.name);
  const audits=await owner.query<{action:string}>("SELECT action FROM audit_events WHERE vendor_id=$1 AND entity_type='route'",[current.vendorId]);for(const action of ['route.created','route.renamed','route.deactivated','route.deleted','route.restored','route.reactivated'])assert.ok(audits.rows.some(row=>row.action===action));
});
