import assert from 'node:assert/strict';
import test from 'node:test';

import type { TransactionContext } from '../src/common/application/transaction-context.js';
import { requestContextStore } from '../src/common/context/request-context.js';
import { DefaultRouteService } from '../src/routing/application/route.service.js';

const tx={}as TransactionContext,actor={userId:'00000000-0000-4000-8000-000000000001',sessionId:'00000000-0000-4000-8000-000000000002',displayName:'Owner',authenticationMethod:'administrator_mfa',platformRoles:[],memberships:[]}as const,route={id:'00000000-0000-4000-8000-000000000010',vendorId:'00000000-0000-4000-8000-000000000011',code:'AM',name:'Morning',deliverySlotId:'00000000-0000-4000-8000-000000000012',status:'active'as const,version:1,createdAt:new Date(),updatedAt:new Date()},assignment={id:'00000000-0000-4000-8000-000000000020',routeId:route.id,deliverySlotId:route.deliverySlotId,agentMembershipId:'00000000-0000-4000-8000-000000000021',serviceDate:'2099-07-20',status:'assigned'as const,createdAt:new Date(),updatedAt:new Date()};
const authorization={execute:(_input:unknown,work:(context:TransactionContext)=>Promise<unknown>)=>work(tx)};
const scheduleDates={lock:()=>Promise.resolve()};
void test('assign validates locked route, slot, and agent then audits safe exact-date state',async()=>{const calls:string[]=[],events:unknown[]=[];const service=new DefaultRouteService(authorization as never,{lockRoot:()=>{calls.push('route');return Promise.resolve(route);}}as never,{}as never,{assign:()=>{calls.push('assign');return Promise.resolve({assignment,routeVersion:2,created:true});}}as never,{requireRouteDeliverySlot:()=>{calls.push('slot');return Promise.resolve({});}}as never,{}as never,{requireRouteAgent:()=>{calls.push('agent');return Promise.resolve({membershipId:assignment.agentMembershipId});}}as never,{getSubscriptionTimezone:()=>Promise.resolve({timezone:'Asia/Kolkata'})}as never,{append:(_tx:TransactionContext,event:unknown)=>{events.push(event);return Promise.resolve();}},scheduleDates);const result=await requestContextStore.run({correlationId:'00000000-0000-4000-8000-000000000030'},()=>service.assign(actor,route.vendorId,route.id,assignment.serviceDate,{agentMembershipId:assignment.agentMembershipId,expectedVersion:1,reason:' Assign route '}));assert.equal(result.routeVersion,2);assert.deepEqual(calls,['route','slot','agent','assign']);const event=events[0]as{action:string;newValue:Record<string,unknown>;reason:string};assert.equal(event.action,'route_assignment.assigned');assert.deepEqual(Object.keys(event.newValue).sort(),['agentMembershipId','assignmentId','deliverySlotId','routeVersion','serviceDate','status']);assert.equal(event.reason,'Assign route');});
void test('cancel does not revalidate route, slot, or agent availability',async()=>{let agent=0,slot=0;const service=new DefaultRouteService(authorization as never,{lockRoot:()=>Promise.resolve({...route,status:'inactive'as const})}as never,{}as never,{cancel:()=>Promise.resolve({assignment:{...assignment,status:'cancelled'as const},routeVersion:2,created:false,previous:assignment})}as never,{requireRouteDeliverySlot:()=>{slot++;return Promise.resolve({});}}as never,{}as never,{requireRouteAgent:()=>{agent++;return Promise.resolve({membershipId:assignment.agentMembershipId});}}as never,{getSubscriptionTimezone:()=>Promise.resolve({timezone:'Asia/Kolkata'})}as never,{append:()=>Promise.resolve()},scheduleDates);await requestContextStore.run({correlationId:'00000000-0000-4000-8000-000000000030'},()=>service.cancelAssignment(actor,route.vendorId,route.id,assignment.serviceDate,{expectedVersion:1,reason:'Cancel route'}));assert.equal(agent,0);assert.equal(slot,0);});
